- name: "配置SSH服务"
  hosts: all
  gather_facts: false
  tasks:
    - name: "拷贝配置文件"
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/ssh/{{ item }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      with_items:
        - sshd_config
        - sshd_banner
    - name: "重启SSH服务"
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true
      changed_when: false
