- name: "配置Redis服务"
  hosts: redis
  gather_facts: false
  tasks:
    - name: "拷贝配置文件 (公用)"
      ansible.builtin.copy:
        src: files/redis-included.conf
        dest: /opt/redis/etc/redis-included.conf
        owner: root
        group: root
        mode: '0644'
    - name: "拷贝配置文件 (6379)"
      ansible.builtin.copy:
        src: files/redis-6379.conf
        dest: /opt/redis/etc/redis-6379.conf
        owner: root
        group: root
        mode: '0644'
    - name: "重启Redis服务 (6379)"
      ansible.builtin.service:
        name: redis-6379
        state: restarted
        enabled: true
      changed_when: false
    - name: "拷贝配置文件 (6380)"
      ansible.builtin.copy:
        src: files/redis-6380.conf
        dest: /opt/redis/etc/redis-6380.conf
        owner: root
        group: root
        mode: '0644'
    - name: "停止Redis服务 (6380)"
      ansible.builtin.service:
        name: redis-6380
        state: stopped
        enabled: false
      changed_when: false
