- name: "配置Redis服务"
  hosts: redis
  gather_facts: false
  tasks:
    - name: "创建安装目录和数据目录"
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,g=rx,o=rx'
      with_items:
        - /opt/redis/
        - /opt/redis/bin/
        - /opt/redis/etc/
        - /opt-data/redis-6379/
        - /opt-data/redis-6380/
        - /opt-data/redis-redlock/
    - name: "拷贝配置文件"
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/opt/redis/etc/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - redis-included.conf
        - redis-6379.conf
        - redis-6380.conf
        - redis-redlock.conf
    - name: "拷贝服务文件"
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      with_items:
        - redis-6379.service
        - redis-6380.service
        - redis-redlock.service
    - name: "Daemon Reload"
      ansible.builtin.systemd:
        daemon_reload: true
    - name: "启动Redis服务 (多个)"
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - redis-6379
        - redis-6380
        - redis-redlock
      changed_when: false
