- name: "设置Docker引擎"
  hosts: docker
  gather_facts: false
  tasks:
    - name: "拷贝配置文件"
      ansible.builtin.copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
    - name: "重启Docker引擎"
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
      changed_when: false
    - name: "更新yingzhuo属组"
      ansible.builtin.user:
        name: yingzhuo
        groups:
          - docker
        append: true
