- name: "初始化乌班图"
  hosts: all
  gather_facts: false
  tasks:
    - name: "安装一些常用软件"
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - zsh
          - zip
          - unzip
          - gcc
          - make
          - automake
          - autoconf
          - g++
          - git
          - figlet
          - net-tools
          - cowsay
          - wget
          - curl
          - libncurses5-dev
          - libncursesw5-dev
          - sysstat
          - libaio-dev
        clean: true
    - name: "关闭防火墙"
      community.general.ufw:
        state: disabled
    - name: "更新/tmp目录权限"
      ansible.builtin.file:
        path: /tmp
        mode: '0777'
        state: directory
    - name: "更新yingzhuo属组"
      ansible.builtin.user:
        name: yingzhuo
        groups:
          - adm
          - sudo
        append: true
