# -------------------------------------------------------------------------------------------------
# 数据库第一次安装后密码是空白字符串。需要以下SQL来重置root密码
#   ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'root';
#   UPDATE mysql.user SET host = '%' WHERE host = 'localhost' AND user = 'root';
#   FLUSH PRIVILEGES;
# -------------------------------------------------------------------------------------------------
- name: "安装和配置MySQL服务"
  hosts: mysql
  gather_facts: false
  tasks:
    - name: "检查MySQL是否已安装"
      ansible.builtin.package_facts:
        manager: auto
    - name: "调试"
      ansible.builtin.debug:
        msg: "MySQL已经安装了"
      when: "'mysql-server' in ansible_facts.packages"
    - name: "退出"
      ansible.builtin.meta: end_play
      when: "'mysql-server' in ansible_facts.packages"
    - name: "安装MySQL服务"
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - mysql-server
        clean: true
    - name: "拷贝配置文件"
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/mysql/mysql.conf.d/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - mysql.cnf
        - mysqld.cnf
    - name: "重启MySQL服务"
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: true
      changed_when: false
    - name: "更新yingzhuo属组"
      ansible.builtin.user:
        name: yingzhuo
        groups:
          - mysql
        append: true
