# -------------------------------------------------------------------------------------------------
# 数据库第一次安装后密码是空白字符串。需要以下SQL来重置root密码
#   ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'root';
#   UPDATE mysql.user SET host = '%' WHERE host = 'localhost' AND user = 'root';
#   FLUSH PRIVILEGES;
# -------------------------------------------------------------------------------------------------
- name: "安装和配置MySQL服务"
  hosts: mysql
  gather_facts: false
  tasks:
    - name: "安装MySQL服务"
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - mysql-server
    - name: "拷贝配置文件 (mysql)"
      ansible.builtin.copy:
        src: files/mysql.cnf
        dest: /etc/mysql/mysql.conf.d/mysql.cnf
        owner: root
        group: root
        mode: '0644'
    - name: "拷贝配置文件 (mysqld)"
      ansible.builtin.copy:
        src: files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: '0644'
    - name: "重启MySQL服务"
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: true
      changed_when: false
    - name: "一般用户添加mysql属组"
      ansible.builtin.user:
        name: yingzhuo
        groups:
          - mysql
        append: true
