# -------------------------------------------------------------------------------------------------
# 初始化Ubuntu
# -------------------------------------------------------------------------------------------------

- name: "初始化乌班图"
  hosts: all
  remote_user: yingzhuo
  tasks:
    - name: "安装一些常用软件"
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - zip
          - unzip
          - gcc
          - make
          - g++
          - git
          - figlet
          - net-tools
          - cowsay
        clean: true
