- name: "安装Docker"
  gather_facts: false
  hosts: docker
  tasks:
    - name: "安装必要的软件"
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true
        clean: true
    - name: "检查公钥文件"
      ansible.builtin.stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: gpg_temp_exists
    - name: "下载GPG公钥"
      ansible.builtin.get_url:
        url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
        dest: /tmp/docker-gpg
        mode: '0400'
      when: "not gpg_temp_exists.stat.exists"
    - name: "信任GPG公钥"
      ansible.builtin.shell:
        cmd: |
          gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker-gpg
      when: "not gpg_temp_exists.stat.exists"
      changed_when: false
    - name: "删除临时文件"
      ansible.builtin.file:
        name: /tmp/docker-gpg
        state: absent
    - name: "拷贝APT清单文件"
      ansible.builtin.copy:
        src: config/docker/apt-docker.list
        dest: /etc/apt/sources.list.d/docker.list
        owner: root
        group: root
        mode: '0644'
      changed_when: false
    - name: "安装DockerEngine"
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true
        clean: true
    - name: "启动Docker服务"
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: "普通账户加入docker属组"
      ansible.builtin.user:
        name: yingzhuo
        groups:
          - docker
        append: true
